#pragma config(Motor,  port2,        motor1    ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,        motor2    ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,        motor3    ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,        motor4    ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,        motor5    ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,        motor6    ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,        motor7    ,             tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


int OFF = 0;

void movement()
//* ------------------------------------------------------------------ *//
//* Refresh motor information to activate and go in any direction value = f(x,y) *//
//* The robot can moves in any directions *//
//* params: none. *//
//* changes: get Axis 3 & 4 values and select values for wheel motors. *//
//* return: this function do not return anything. *//
//* ------------------------------------------------------------------ *//
{
	int x, y;
	x = vexRT[Ch4];
	y = vexRT[Ch3];
	motor[motor6] = -(x+y);
	motor[motor5] = -(-x+y);
	motor[motor4] = -(x-y);
	motor[motor7] = x+y;
}

void allInOff()
//* ------------------------------------------------------------------ *//
//* Refresh motor information to deactivate value = OFF *//
//* param: none. *//
//* changes: array motor values equal global variable OFF. *//
//* return: this function do not return anything. *//
//* ------------------------------------------------------------------ *//
{
	motor[motor1] = OFF;
	motor[motor2] = OFF;
	motor[motor3] = OFF;
	motor[motor4] = OFF;
	motor[motor5] = OFF;
	motor[motor6] = OFF;
	motor[motor7] = OFF;
}


task main()
{
	while(1)
	{
		movement();
		if(vexRT[Btn7D] == 1)
		{
			motor[motor1] = 100;
			motor[motor2] = -100;
		}
		if(vexRT[Btn7U] == 1)
		{
			motor[motor1] = -100;
			motor[motor2] = 100;
		}
		if(vexRT[Btn8U] == 1)
		{
			motor[motor3] = -100;
		}
		if(vexRT[Btn8D] == 1)
		{
			motor[motor3] = 100;
		}
		sleep(100);
		allInOff();
	}

}
